dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker-compose -f docker-compose-build.yml build
      - echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_LOGIN} --password-stdin && docker-compose -f docker-compose-build.yml push
