version: "3.4"
x-postgres-env-config: &x-postgres-env-config
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "${POSTGRES_HOST}"

services:

  postgis:
    image: monstrofil/postgis_hstore
    restart: unless-stopped
    build:
      context: postgis
    environment:
      <<: *x-postgres-env-config
    volumes:
      - pg_renderd_data:/var/lib/postgresql/data/
    depends_on:
      - tegola

  tegola:
    build:
      context: vector
    restart: unless-stopped
    entrypoint: /bin/wait_for postgis:5432 -- /opt/tegola serve --config /opt/config.toml
    volumes:
      - ./config/tegola_simple.toml:/opt/config.toml:ro
      - ./wait_for.sh:/bin/wait_for:ro
      - tegola:/persistent/
    ports:
    - 8090:3002

  imposm:
    build:
      context: imposm
    environment:
      <<: *x-postgres-env-config
    command: /bin/wait_for postgis:5432 -- manage update
    depends_on:
      - postgis
    volumes:
      - diffdir:/diffdir
      - ./wait_for.sh:/bin/wait_for:ro
      - ./data:/import:ro
      - ./config:/config:ro

  web:
    build:
      context: web
      target: nginx
    ports:
    - 6666:80

  backend:
    build:
      context: backend
    volumes:
    - ./backend/app:/app:ro
    environment:
      <<: *x-postgres-env-config
    ports:
    - 6667:80

volumes:
  pg_renderd_data:
  diffdir:
  tegola: